variables:
  ARM_PASS: $(adminPass)

trigger:
- none

pool:
  name: pool-1

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'quickstarts/microsoft.web/webapp-linux-managed-mysql/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Sub - Resource Group 1'
    subscriptionId: 'ddcb21c8-6540-4cc3-a842-f20522b6f2f6'
    action: 'DeleteRG'
    resourceGroupName: 'Resource_Group_1'
    location: 'Australia East'
    
